# -*- mode:org; fill-column:79; -*-

* How Computers Work
  :PROPERTIES:
  :Length:   16:33
  :Section:  2
  :Section-Name: Essential Fundamentals
  :END:
#+begin_export texinfo
@ifhtml
@url{../Lectures/Section_02-Essential_Fundamentals/03.How_Computers_Work.mp4,Lecture 03.How Computers Work}
@end ifhtml
#+end_export

For understanding how computers looks at first of all let us look at A Blog
data.  It's a very basic thing.  Let us study it.  See there's a blog them off
your computer.  Let us see the computer first of all.  See this the CBO is
having to pass a view that is automatic and logical union and control unit.
See you.  I'll explain they're working the next US main memory and this is the
hard disk drive which contains the data in the form of files and this is input
device like a keyboard mouse or a stylus tablet anything then the output device
like your monitor or printer and speakers.  Now let us understand that working
see the heart of the computer is the Cebu that is central processing unit or
micro processing or if you present day processing if you see that is i3 i.e. 5
7 these processes.  Now this part processor will have to box that is ultimately
a logical unit and control unit.  So what is that automatic ideological unit
can perform automatically and logical operations a basic operation so a
computer can perform basic operations like automatic operations like addition
subtraction multiplication or division or modulus then under logical operations
it can compare to numbers we can compare less then greater than or equal to an
also it can perform logical operations and are these operations like this
written in caps so and and are as follows not.  So these are the logical
operations basically.  So it can perform just these basic operations right
then.  Second is C you control unit C there are other things connected like
Hard Disk Drive and the main memory in devise is an output device for
controlling all these things.  Controlling means utilizing them so far back it
is having a separate portion that is called control unit.  So its job is to
utilize other resources.  This is about processing now.  Next thing let us
start from here.  This is hard disk hard disk will contain files on those files
maybe two types.  Either program files are data files like if you take for
example a notepad on your P.C. as a program file when you open notepad.  It's a
program.  So there is a file of a level.  Basically we click on some like and
then the program will start.  But if you look at my computers and folders and
some very you will find a program for in your bag and its name file name will
be known by the dog.  E XY if you search for ID you can find this fine does a
program file No inside no body for type something and save then it will be
saving it as a text file so you may be saving you does my daughter.  Steve fine
right.  So this is a program 5 and this is a bit off high.  This data file is
used by notepad or generated by north back.  So finally hardest contains two
types of files program files and data files.  If you have audio files or music
files or video files all those comes on the data files and if you have a music
player like VANOC player or media player those come said the program.  So he
start a lot of programs kept inside Hardy's apartment in storage and this will
be larger insights.  The next is suppose we want to run any program then that
program should be present inside the main memory so that you can execute it.
So the program is brought from the hardest to the main memory.  It is brought
from hardness to the main memory.  So this is a working memory.  Our primary
memory out of work space.  So programs should be brought here.  Then you can
execute the program by taking instructions.  Line by line for whatever the
programs we on they are brought here inside the main memory right.  Then if a
program needs to some data from keyboard or it has to display something on the
monitor then it can utilize this input devices are pretty wireless.  So the
program may be taking something from keyboard or remember taking something from
Internet or maybe reading something from the file.  So if program needs to some
data it would be getting it from here.  Whatever the result is generated by the
program or interactivity provided by a program that you can find it on the
output device like monitor or if any output for it is printed on the printer
and these input and output devices are connected to the system and they have
the own memory like I'm sure you'd like this.  This is the memory belongs to
input device and the memory belongs to the device.  So this I will call it guys
input buffer as a buffer.  Does the memory and similarly that is output buffer
does is output buffer.  So if a program has to read something from the keyboard
so it will go to memory area and get the data from there.  I think it has to be
something on the monitor then whatever it has to print it will put it in its
memory area called s buffer Oakwood buffer.  It's not that program robotically
go and bring something on the monitor it will dumb everything inside the frame
that is the frame before or output buffer.  And that will appear on the screen
now send me whatever typing from the keyboard that will go and file inside the
buffer it directly doesn't enter into the program.  It will go on and fall into
the buffer and the program can read the contents from the buffer so there's a
communication point for the devise and a program running inside the in memory
now.  So that's it.  One of the important thing we have an Easter holiday work
altogether.  So once again I repeat quickly the programs are here.  They have
to be brought into the main memory for execution and we will execute them by
executing instructions line by line.  And if program requests for interactive
interact with the user and users input and output devices.  Now we will learn
how that CQ works how that works.  Howard understand what does it mean by
instruction hard to get an instruction.  So for this let us start from the
basics.  See number the works on the binary number system.  What is binary
system right works on binary system C it's an electronic device.  So it works
on current or wall digits.  So working just order particularly or logically
used as a binary.  How are low level working low water they just stick them at
zero and high voltage is treated as one.  So it is just like if suppose you
have a bulb does a bulb right this bulb can be off or a bulb can be either on
if it is on then we treat it as one if it is off we do it because evil fine.
Now if you have seen electronic circuitry like ICD I will droid here.  If you
look at the electronic circuitry like this an icy light integrated circuit this
is a com.  It is also called as a chip.  You can see the photograph also here
and I have taken the same example.  Now just on the integrated circuit it is
having pins here these are pins this is electronic right now.  Toward these
pins we can pass some more digits right.  Some mortgage.  So in this one
particular pin we can pass either lower to age or we can pass high voltage
lower basements size zero and a high voltage is one.  Now this is maybe taking
in and storing it audit moving it sending it out through this other pin the
other end for how it works and all we don't have to go in detail just we have
to focus on binary form right.  So this one pin can be that easy or fun.
Right.  So only two possibilities are there.  So that's how this is binary.  So
we say does that binary number system and we call this as one the bit we call
it does one bit.  So this is.  But then if I count one two three four five six
seven eight eight which side.  So this together a bit silly putty does one bite
so 8 binary bits.  Now all of these bits are zeros mints of the low work age.
So this is 0 0 0 0 is 0 are all those eight bits are zero but only the last bit
is one.  So this will be like this are some odd zeros and some are ones.
Right.  So there can be many combinations not eight bits together aid bits
together.  These are forming this pattern.  They can form various backgrounds
not each pattern of bits we can take it as an instruction pattern of bits of
that is in binary form and we can take it as an instruction how it is treated
as instruction I'll explain I'll remove this and explain you see if there is
one bulb then that a bulb can be either on or off.  Now if you look at traffic
signals and if you consider only one bulb there usually will have three
different lights.  Let us assume there is only one bulb.  God bulbous for only
two things.  It can be used only for two things.  The Osmonds should stop if it
is on mints you can call or other.  If you say little if it is on mints you
should stop off mint you shouldn't.  Whatever it is whatever you like.  You can
set it so we can set the rule and you can communicate with the people that this
will be the go order.  That will be followed.  There will be only one bulb.
And if it is on mints you can go.  It is off limits.  You should stop looking
like this we can use this tape of course at many places like suppose Oh Officer
is there in his office.  So bulbs on he's there.  If it is often he's not there
like or if a shop is there.  Bulbs on man shoppers open bulbs often.  Shop is
closed.  Like this.  This gives some message this gives the courts so.  Same
thing.  Electronic circuitry is having more digits 0 or governments on and off
using these four digits.  You can make some communication.  So one bulb can
give you two messages right.  Go.  Or stop shop is open or closed like that.
If you increase the bulbs.  So let us take two bulbs if you have two bulbs then
what are the combinations possible with the two bulbs both the bulbs are off.
Right.  Are these bulbs on.  Are this bulbs on are both our on statements.
This is giving four different messages for different messages to bulbs can give
you together four different messages.  So if you have to communicate four
things for the people then you can have two bulbs and you can set them on and
off and you could already educate the people and say that this means this.
This means that slams like example in an examination if it's a multiple choice
question paper.  Now students want to copy them.  Now if one of the person
knows Don so he can communicate to others for that they already said the
chords.  Like if I scratch here it means option a if I do it like this rub my
eyes then it does option B.  Like that they can set the chords beforehand to
set the chords and they can understand it in the examination hall.  So same
thing.  Now similarly we can use to bulk for giving more messages.  So if there
are three bulbs then what if there are three bolts but just unscrambling 4 0 0
0 people how many possibilities are there.  So this is two 14 eight
possibilities out there right.  So it means what about four bolts.  If you have
have four bolts then this is two or four sixteen.  And what if we have eight
bolts.  So eight bolts will be two part aid that that is 256 so we can have
different 256 different come ons to fifty six different messages messages.  So
that's it.  So the computer system works on binary the number system.  This
bulbs are nothing but the pins.  And I suppose there are eight pins like this
an AC so it is just eight pin slot each pin you assume that it's a bulb.  And
that can be on and off to the loop and can have different commands like 256
different commands.  So messages are commands.  So in the same way this CPE was
also built up on messages that are in the form of binary that is lower than
your high voltage that is on and off.  We'll see more on this one.  I'll label
this and discuss further so that we can say that the language of computers is
binary they understand binary language that is in the form of zeros and ones
that is lower than your heritage.  So all the instructions and the data
everything should be in the form of binary sort of language of the CPS binary
so hard to perform arithmetic and logical operation it performs operation on
binary number system.  So that I can see that the language of machine or the
computer is binary but we understand the human number system.  We are not
comfortable with binding it in my system read before working in the decimal
number system.  So in combination with the decimal number system Howard is
equal to binary form.  Let us look at it a little bit.  See in decimal number
system we have the digits from 0 1 2 3.  So on 2 9 we use these digits to form
unknown but then by the new number system there are only two numbers that are
zeros and ones.  So anything we want we want to understand in the form of
decimal.  So in decimal form of four to zero then it is binary also zero if it
is one then it is onto one then in decimal it is two in binary it is 1 2 and 3
is one 1 food as 1 0 0 5 is 1 0 1 and so on.  So this is the binary form of
these decimal numbers not based on decimal number system we understand that
this CB You are the ultimate technological unit perform operations so ignores
the instructions ignores commands like zero means I suppose like a zoom that
zero means are the two numbers one means subtract two numbers tomans multiply
them like this they are forming instructions so there are some predefined
instructions that are there inside that circuitry electronic circuitry and that
is logically designed to work in mines so the commands that we already know we
have seen that it can perform automatic and logical operations those operations
are given in the form of codes and it already knows that which command means
what I have to do and VDI the programs in the form of binary so the programs
must be present inside the main memory in the form of binary so each line of
program that is an instruction it will simply take an instruction and execute
it because it already knows what it has to do for which record.  For like these
becomes the courts as instructions for performing specific instruction.  So if
you study some machine language or low level language of computer system you
can understand that its instructions are in the form of binary right.  So
that's on the end here.  The conclusion of the stock as how computer works come
to work fun binary number system right.  And why they work on binary system
because they are based on electronic and electronic signal Saudi that is zero
or one that is low or high.  So that cell everything is built up on binary.  If
we don't understand binary number system so to know how it is related to a
decimal system we should understand some number systems in the next video we
will discuss about number systems.
